server.port=8080

# MongoDB Atlas (fallback to local if env variable not set)
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://devashreenasare_db_user:ZA3AqKU30ZH429wb@cluster0.cmverb3.mongodb.net/smart_clinic?retryWrites=true&w=majority&appName=Cluster0}

# SMS API Credentials (Fast2SMS)
sms.api.key=YyAj6sW5XQOr7lqve1nuBFhT2KbDi9pz4mkxNaPgJGfL0RZHdwoV0dhIQqwTbysDkZgOmLePGW39jYz8

spring.main.allow-bean-definition-overriding=true
